{
 "title": "Sample Dashboard - nodelete",
 "time": { "from": "2022-01-14T15:00:00.000Z", "to": "2022-04-05T14:59:59.000Z" },
 "panels": [
  {
   "title": "Activity Score 📈 : 0x649be1c4dface544857e54d5c3fbdb8152b84b4e",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "amount",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "amount", "id": "1", "type": "avg" }
     ],
     "query": "from:0x649be1c4dface544857e54d5c3fbdb8152b84b4e",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "UserTransferRanking - Symbol : MATIC",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "from.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "amount", "id": "1", "type": "sum" }
     ],
     "query": "symbol:MATIC",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Transaction Method Diversity Score - from : 0xd537c667d491949f0657102f56b077050aa7805f",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "method.keyword",
       "id": "4",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "symbol.keyword", "id": "3", "type": "cardinality" }
     ],
     "query": "from: 0x649be1c4dface544857e54d5c3fbdb8152b84b4e",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Method statistics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "method.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top10 Token Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "symbol.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TotalTradingAmount",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "amount", "id": "1", "type": "avg" }
     ],
     "query": "*",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}